# GitHub Pages Configuration for Roman's Rater 4.21

# Site settings
title: "Roman's Rater 4.21"
description: "Professional Auto Liability Insurance Rating Engine"
author: "Your Name"
email: your.email@example.com

# Build settings
markdown: kramdown
theme: null  # Using custom HTML/CSS

# GitHub Pages specific
url: "https://dmedina5.github.io"
baseurl: "/romans-rater"

# Exclude from processing
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - .gitignore
  - node_modules/
  - vendor/

# Include files
include:
  - _config.yml

# Collections
collections:
  docs:
    output: true
    permalink: /docs/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
twitter:
  username: dmedina5
  card: summary_large_image

social:
  name: Roman's Rater
  links:
    - https://github.com/dmedina5/romans-rater

logo: /assets/images/logo.png

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X

# Additional settings
lang: en
timezone: America/New_York
